# Generated by Django 4.2.4 on 2023-08-31 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=100)),
                ("age", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("lastName", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("gender", models.CharField(max_length=100)),
                ("school", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=100)),
                ("bio", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="HomeModel",
        ),
    ]
