# Generated by Django 4.2.4 on 2023-08-31 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_usermodel_delete_homemodel"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserModel",
            new_name="UsrModel",
        ),
    ]
