# Generated by Django 4.2 on 2023-08-22 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schools',
            name='numOfStudents',
            field=models.IntegerField(),
        ),
    ]
