# Generated by Django 4.2 on 2023-08-28 01:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_schools_numofstudents'),
    ]

    operations = [
        migrations.AddField(
            model_name='schools',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
