# Generated by Django 4.2.4 on 2023-08-24 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand",
                    models.CharField(max_length=50, verbose_name="Marca del carro: "),
                ),
                ("specifications", models.TextField(verbose_name="Especificaciones")),
                (
                    "created_at",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de consulta: "
                    ),
                ),
            ],
        ),
    ]
