# Generated by Django 4.2.4 on 2023-08-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RecetaModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("ingredients", models.TextField()),
                ("procedure", models.TextField()),
                ("published", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
