# Generated by Django 4.1.7 on 2023-08-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userApp',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('nation', models.CharField(max_length=100)),
                ('study', models.CharField(max_length=100)),
            ],
        ),
    ]
