# Generated by Django 4.2.4 on 2023-08-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pcmaster",
            name="FechaConsulta",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de consulta"
            ),
        ),
        migrations.AlterField(
            model_name="pcmaster",
            name="FuentePoder",
            field=models.CharField(max_length=50, verbose_name="Fuente de poder"),
        ),
        migrations.AlterField(
            model_name="pcmaster",
            name="NumVentiladores",
            field=models.IntegerField(verbose_name="Numero de ventiladores"),
        ),
        migrations.AlterField(
            model_name="pcmaster",
            name="procesador",
            field=models.CharField(max_length=50, verbose_name="Procesador"),
        ),
        migrations.AlterField(
            model_name="pcmaster",
            name="tarjetaGrafica",
            field=models.CharField(max_length=50, verbose_name="Grafica"),
        ),
    ]
