# Generated by Django 4.1.7 on 2023-08-24 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="telefonoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("brand", models.CharField(max_length=50)),
                ("quantity", models.BigIntegerField()),
            ],
        ),
    ]
