# Generated by Django 3.2.12 on 2023-08-28 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='age',
            field=models.IntegerField(verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='edu_lvl',
            field=models.TextField(verbose_name='Máximo nivel educativo'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='gender',
            field=models.TextField(verbose_name='Género'),
        ),
    ]
