# Generated by Django 3.2.12 on 2023-08-28 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20230828_0243'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserModel',
            new_name='StudentModel',
        ),
    ]
