# Generated by Django 4.2.4 on 2023-08-29 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=10)),
                ("address", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("date", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Custom Model",
                "verbose_name_plural": "Custom Models",
                "ordering": ["name"],
            },
        ),
    ]
