# Generated by Django 4.2.4 on 2023-08-29 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='content',
            new_name='activity',
        ),
    ]
