# Generated by Django 4.2.4 on 2023-09-04 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=50)),
                ('descripcion', models.CharField(default='', max_length=350)),
                ('tokens', models.IntegerField(default=-1)),
            ],
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
